name: Lint

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  consistent:
    name: consistent
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: consistent
        run: go run github.com/blizzy78/consistent/cmd/consistent@latest ./...
