name: VulnCheck

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  vulncheck:
    name: vulncheck
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: vulncheck
        uses: golang/govulncheck-action@v1
